/**
	Generated by sails-inverse-model
	Date:Wed Jun 26 2019 15:55:14 GMT+0100 (Western European Summer Time)
*/

module.exports = {
    attributes: {
        id: {
            type: "number",
            columnName: 'id_comentario',
            columnType: "int",
            isInteger: true,
            required: true
        },
        motivo: {
            type: "string",
            columnType: "varchar",
            maxLength: 64
        },
        observacao: {
            type: "string",
            columnType: "varchar",
            maxLength: 255
        },
        reportado_por: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        }
    }
};