/**
	Generated by sails-inverse-model
	Date:Mon May 27 2019 15:05:05 GMT+0100 (Western European Summer Time)
*/
/*
create table comentario(
    id int unsigned PRIMARY KEY,
    id_especie int unsigned not null,
    num_comentario int not null,
    data_hora datetime not null,
    id_user varchar(64) not null,
    resposta_a int,
    FOREIGN KEY(id_especie) REFERENCES especie(id_especie)
);
*/
module.exports = {
    migrate: 'safe',
    attributes: {
        id: {
            type: "number",
            columnName: 'id',
            columnType: "int",
            isInteger: true,
            autoIncrement: true
        },
        id_especie: {
            model: "especie",
            required: true  
        },
        num_comentario: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        comentario: {
            type: "string",
            columnType: "varchar",
            maxLength: 255,
            required: true
        },
        data_hora: {
            type: "ref",
            columnType: "datetime",
            required: true
        },
        id_utilizador: {
            model: "utilizador",
            required: true
        },
        resposta_a: {
            type: "number",
            columnType: "int",
            isInteger: true,
            defaultsTo: -1
        }
    }
};