/**
	Generated by sails-inverse-model
	Date:Mon May 27 2019 15:05:05 GMT+0100 (Western European Summer Time)
*/

module.exports = {
    migrate: 'safe',
    attributes: {
        id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            autoIncrement: true
        },
        genero: {
            model: "genero"
        },
        nome: {
            type: "string",
            columnType: "varchar",
            maxLength: 32
        },
        sub_especie: {
            type: "string",
            columnType: "varchar",
            maxLength: 16
        },
        nomes_comuns: {
            type: "string",
            columnType: "varchar",
            maxLength: 256
        },
        caracteristicas: {
            type: "string",
            columnType: "text"
        },
        imagem_ciclo: {
            type: "string",
            columnType: "varchar",
            maxLength: 64
        },
        wiki_link: {
            type: "string",
            columnType: "varchar",
            maxLength: 64
        },
        ecologia: {
            type: "string",
            columnType: "varchar",
            maxLength: 256
        },
        origem: {
            type: "string",
            columnType: "varchar",
            maxLength: 256
        },
        distribuicao: {
            type: "string",
            columnType: "varchar",
            maxLength: 256
        },
        utilizacoes: {
            type: "string",
            columnType: "varchar",
            maxLength: 256
        },
        observacoes: {
            type: "string",
            columnType: "varchar",
            maxLength: 256
        },
        referencias: {
            type: "string",
            columnType: "text"
        },
        n_pesquisas: {
            type: "number",
            columnType: "int",
            isInteger: true
        },
    }
};