/**
	Generated by sails-inverse-model
	Date:Wed Jun 26 2019 15:55:14 GMT+0100 (Western European Summer Time)
*/

module.exports = {
    attributes: {
        id: {
            type: "number",
            columnName: 'id_foto',
            columnType: "int",
            isInteger: true,
            required: true
        },
        id_utilizador: {
            type: "number",
            columnType: "int",
            isInteger: true,
            required: true
        },
        is_liked: {
            type: "number",
            columnType: "tinyint",
            isInteger: true,
            required: true
        }
    }
};