/**
	Generated by sails-inverse-model
	Date:Mon May 27 2019 15:05:05 GMT+0100 (Western European Summer Time)
*/

module.exports = {
    migrate: 'safe',
    attributes: {
        id: {
            type: "number",
            columnType: "int",
            isInteger: true,
            autoIncrement: true
        },
        id_especie: {
            model: "especie",
            required: true
        },
        nome_ficheiro: {
            type: "string",
            columnType: "varchar",
            maxLength: 64,
            required: true
        },
        foto_capa: {
            type: "number",
            columnType: "tinyint",
            isInteger: true,
            defaultsTo: 0
        },
        is_validated: {
            type: "number",
            columnType: "tinyint",
            isInteger: true,
            defaultsTo: 0
        },
        adicionada_por: {
            model: "utilizador",
            required: true
        },
        avaliacao: {
            type: "number",
            columnType: "int",
            defaultsTo: 0
        }
    }
};