/**
	Generated by sails-inverse-model
	Date:Mon May 27 2019 15:05:05 GMT+0100 (Western European Summer Time)
*/

module.exports = {
    migrate: 'safe',
    attributes: {
        familia: {
            model: "familia"
        },
        id: {
            type: "string",
            columnName: 'nome',
            columnType: "varchar",
            maxLength: 16,
            required: true
        },
        wiki_link: {
            type: "string",
            columnType: "varchar",
            maxLength: 64
        },
        n_pesquisas: {
            type: "number",
            columnType: "int",
            isInteger: true
        },
    }
};