/**
	Generated by sails-inverse-model
	Date:Mon May 27 2019 15:05:05 GMT+0100 (Western European Summer Time)
*/
/*

create or replace table sugestoes (
    id int unsigned AUTO_INCREMENT PRIMARY KEY,
    nome varchar(32) PRIMARY KEY,
    tipo varchar(32),
    info varchar(256)
);

*/
module.exports = {
    migrate: 'safe',
    attributes: {
        id: {
            type: "number",
            columnName: 'id',
            columnType: "int",
            isInteger: true,
            autoIncrement: true
        },
        nome: {
            type: "string",
            columnType: "varchar",
            maxLength: 31,
            required: true
        },
        tipo: {
            type: "string",
            columnType: "varchar",
            maxLength: 31,
            required: true
        },
        info: {
            type: "string",
            columnType: "varchar",
            maxLength: 255,
        }
    }
};